exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - package.json
  - node_modules
  - gulpfile.js

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Mãos de amar
subtitle: "Doula, aleitamento materno, shantala e massagem materna"
description: Doula, amamentação, shantala, massagem em bebê e massagem pré e pós parto.
encryptedemail: "e r i k a p e r r o n i @ g m a i l . c o m"
email: "erikaperroni@gmail.com"
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: "https://www.maosdeamar.com.br" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"
image: "../img/bg2.jpg"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-90570639-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
